const VERSION = '1.0.2';
const WRAP_BIND_KEY_FLAG = 2;
const LAZY_FILTER_FLAG = 1;
const LAZY_WHILE_FLAG = 3;
const MAX_ARRAY_LENGTH = 4294967295;

export {
    VERSION,
    WRAP_BIND_KEY_FLAG,
    LAZY_FILTER_FLAG,
    LAZY_WHILE_FLAG,
    MAX_ARRAY_LENGTH
};
